api_platform:
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Presentation/Api']
    title: API Platform
    version: 1.0.0
    defaults:
        stateless: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
